CREATE LOGIN [swimsadmin]
    WITH PASSWORD = N'qgkyk0vrr|dwzove{o0wvUhjmsFT7_&#$!~<~lulspluo$dk', SID = 0xC450138A60E6BD4C813E6ACB2F9B030E, DEFAULT_DATABASE = [SWIMS_CUSTOMER], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

